In [1]:
# https://www.kaggle.com/datasets/smid80/weatherww2

In [2]:
import pandas as pd

In [3]:
df_weather = pd.read_csv("00_files/01_summary_of_weather.csv", low_memory=False)
df_stations = pd.read_csv("00_files/02_weather_station_locations.csv")

In [4]:
df_weather.head()

,STA,Date,Precip,WindGustSpd,MaxTemp,MinTemp,MeanTemp,Snowfall,PoorWeather,YR,...,FB,FTI,ITH,PGT,TSHDSBRSGF,SD3,RHX,RHN,RVG,WTE
0,10001,1942-7-1,1.016,NaN,25.555556,22.222222,23.888889,0,NaN,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10001,1942-7-2,0,NaN,28.888889,21.666667,25.555556,0,NaN,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10001,1942-7-3,2.54,NaN,26.111111,22.222222,24.444444,0,NaN,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10001,1942-7-4,2.54,NaN,26.666667,22.222222,24.444444,0,NaN,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10001,1942-7-5,0,NaN,26.666667,21.666667,24.444444,0,NaN,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_stations.head()

,WBAN,NAME,STATE/COUNTRY ID,LAT,LON,ELEV,Latitude,Longitude
0,33013,AIN EL,AL,3623N,00637E,611,36.383333,6.650000
1,33031,LA SENIA,AL,3537N,00037E,88,35.616667,0.583333
2,33023,MAISON BLANCHE,AL,3643N,00314E,23,36.716667,3.216667
3,33044,TELERGMA,AL,3607N,00621E,754,36.116667,6.416667
4,12001,TINDOUF,AL,2741N,00809W,443,27.683333,-8.083333

In [6]:
df_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119040 entries, 0 to 119039
Data columns (total 31 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   STA          119040 non-null  int64
 1   Date         119040 non-null  object
 2   Precip       119040 non-null  object
 3   WindGustSpd  532 non-null     float64
 4   MaxTemp      119040 non-null  float64
 5   MinTemp      119040 non-null  float64
 6   MeanTemp     119040 non-null  float64
 7   Snowfall     117877 non-null  object
 8   PoorWeather  34237 non-null   object
 9   YR           119040 non-null  int64
 10  MO           119040 non-null  int64
 11  DA           119040 non-null  int64
 12  PRCP         117108 non-null  object
 13  DR           533 non-null     float64
 14  SPD          532 non-null     float64
 15  MAX          118566 non-null  float64
 16  MIN          118572 non-null  float64
 17  MEA          118542 non-null  float64
 18  SNF          117877 non-null  object
 19  SND          5563 non-null    float64
 20  FT           0 non-null       float64
 21  FB           0 non-null       float64
 22  FTI          0 non-null       float64
 23  ITH          0 non-null       float64
 24  PGT          525 non-null     float64
 25  TSHDSBRSGF   34237 non-null   object
 26  SD3          0 non-null       float64
 27  RHX          0 non-null       float64
 28  RHN          0 non-null       float64
 29  RVG          0 non-null       float64
 30  WTE          0 non-null       float64
dtypes: float64(20), int64(4), object(7)
memory usage: 28.2+ MB

In [7]:
df_stations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   WBAN              161 non-null    int64
 1   NAME              161 non-null    object
 2   STATE/COUNTRY ID  161 non-null    object
 3   LAT               161 non-null    object
 4   LON               161 non-null    object
 5   ELEV              161 non-null    int64
 6   Latitude          161 non-null    float64
 7   Longitude         161 non-null    float64
dtypes: float64(2), int64(2), object(4)
memory usage: 10.2+ KB

In [8]:
df_weather.describe()

,STA,WindGustSpd,MaxTemp,MinTemp,MeanTemp,YR,MO,DA,DR,SPD,...,FT,FB,FTI,ITH,PGT,SD3,RHX,RHN,RVG,WTE
count,119040.000000,532.000000,119040.000000,119040.000000,119040.000000,119040.000000,119040.000000,119040.000000,533.000000,532.000000,...,0.0,0.0,0.0,0.0,525.000000,0.0,0.0,0.0,0.0,0.0
mean,29659.435795,37.774534,27.045111,17.789511,22.411631,43.805284,6.726016,15.797530,26.998124,20.396617,...,NaN,NaN,NaN,NaN,12.085333,NaN,NaN,NaN,NaN,NaN
std,20953.209402,10.297808,8.717817,8.334572,8.297982,1.136718,3.425561,8.794541,15.221732,5.560371,...,NaN,NaN,NaN,NaN,5.731328,NaN,NaN,NaN,NaN,NaN
min,10001.000000,18.520000,-33.333333,-38.333333,-35.555556,40.000000,1.000000,1.000000,2.000000,10.000000,...,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
25%,11801.000000,29.632000,25.555556,15.000000,20.555556,43.000000,4.000000,8.000000,11.000000,16.000000,...,NaN,NaN,NaN,NaN,8.500000,NaN,NaN,NaN,NaN,NaN
50%,22508.000000,37.040000,29.444444,21.111111,25.555556,44.000000,7.000000,16.000000,32.000000,20.000000,...,NaN,NaN,NaN,NaN,11.600000,NaN,NaN,NaN,NaN,NaN
75%,33501.000000,43.059000,31.666667,23.333333,27.222222,45.000000,10.000000,23.000000,34.000000,23.250000,...,NaN,NaN,NaN,NaN,15.000000,NaN,NaN,NaN,NaN,NaN
max,82506.000000,75.932000,50.000000,34.444444,40.000000,45.000000,12.000000,31.000000,78.000000,41.000000,...,NaN,NaN,NaN,NaN,23.900000,NaN,NaN,NaN,NaN,NaN

In [9]:
df_stations.describe()

               WBAN         ELEV    Latitude   Longitude
count    161.000000   161.000000  161.000000  161.000000
mean   33421.440994   439.850932   20.347205    8.364182
std    20826.534394  1745.422339   21.042992   87.420419
min    10001.000000     1.000000  -27.600000 -175.000000
25%    13601.000000     9.000000    8.233333  -60.850000
50%    32906.000000    27.000000   22.333333    9.083333
75%    34150.000000    98.000000   36.116667   67.250000
max    82506.000000  9999.000000   67.016667  177.366667

In [10]:
df_weather.drop(["WindGustSpd", "PoorWeather", "DR", "SPD", "SND","FT", "FB", "FTI", "ITH", "PGT", "TSHDSBRSGF", "SD3", "RHX", "RHN", "RVG", "WTE" ], axis=1, inplace=True)

In [11]:
df_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119040 entries, 0 to 119039
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   STA       119040 non-null  int64
 1   Date      119040 non-null  object
 2   Precip    119040 non-null  object
 3   MaxTemp   119040 non-null  float64
 4   MinTemp   119040 non-null  float64
 5   MeanTemp  119040 non-null  float64
 6   Snowfall  117877 non-null  object
 7   YR        119040 non-null  int64
 8   MO        119040 non-null  int64
 9   DA        119040 non-null  int64
 10  PRCP      117108 non-null  object
 11  MAX       118566 non-null  float64
 12  MIN       118572 non-null  float64
 13  MEA       118542 non-null  float64
 14  SNF       117877 non-null  object
dtypes: float64(6), int64(4), object(5)
memory usage: 13.6+ MB

In [12]:
df_stations.drop(["LAT", "LON"], axis=1, inplace=True)

In [13]:
df_stations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   WBAN              161 non-null    int64
 1   NAME              161 non-null    object
 2   STATE/COUNTRY ID  161 non-null    object
 3   ELEV              161 non-null    int64
 4   Latitude          161 non-null    float64
 5   Longitude         161 non-null    float64
dtypes: float64(2), int64(2), object(2)
memory usage: 7.7+ KB

In [14]:
df_merged = df_weather.merge(df_stations, left_on="STA", right_on="WBAN", how="left")

In [15]:
df_merged.drop(columns=["WBAN"], inplace=True)

In [16]:
df_merged.head()

,STA,Date,Precip,MaxTemp,MinTemp,MeanTemp,Snowfall,YR,MO,DA,PRCP,MAX,MIN,MEA,SNF,NAME,STATE/COUNTRY ID,ELEV,Latitude,Longitude
0,10001,1942-7-1,1.016,25.555556,22.222222,23.888889,0,42,7,1,0.04,78.0,72.0,75.0,0,ACCRA,GH,62,5.6,-0.3
1,10001,1942-7-2,0,28.888889,21.666667,25.555556,0,42,7,2,0,84.0,71.0,78.0,0,ACCRA,GH,62,5.6,-0.3
2,10001,1942-7-3,2.54,26.111111,22.222222,24.444444,0,42,7,3,0.1,79.0,72.0,76.0,0,ACCRA,GH,62,5.6,-0.3
3,10001,1942-7-4,2.54,26.666667,22.222222,24.444444,0,42,7,4,0.1,80.0,72.0,76.0,0,ACCRA,GH,62,5.6,-0.3
4,10001,1942-7-5,0,26.666667,21.666667,24.444444,0,42,7,5,0,80.0,71.0,76.0,0,ACCRA,GH,62,5.6,-0.3

In [17]:
df_merged.to_csv("00_files/03_weather_ww2_merged.csv", index=False)