In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("00_files/07_bank_customers.csv")

In [3]:
df.head()

,age,job_satisfaction,balance,duration_last_call,num_contacts_last_month,has_housing_loan,has_personal_loan,communication_type,days_since_last_contact,campaign_response_score,subscribed
0,-0.377957,1.043895,1.043494,-0.101838,-1.617442,0.402713,0.913601,-0.067192,0.175471,-1.049646,0
1,-0.325259,1.276263,-0.686123,-2.463205,-0.489426,-0.240715,-1.469496,1.006633,-0.833692,0.957744,0
2,0.739019,-0.600903,-0.177294,1.335714,-0.817332,-0.790047,1.457365,-0.218981,0.878643,-1.257740,0
3,0.474312,-1.103002,1.189936,-0.800186,0.912377,-0.406451,-1.130950,1.985111,1.379029,1.041768,1
4,0.927365,1.114796,0.080284,1.261064,0.761179,0.921563,0.440832,0.184645,-1.567739,-0.142107,1

In [4]:
df.describe()

,age,job_satisfaction,balance,duration_last_call,num_contacts_last_month,has_housing_loan,has_personal_loan,communication_type,days_since_last_contact,campaign_response_score,subscribed
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,-0.015084,0.031559,0.045069,-0.020771,0.016769,-0.042135,-0.025139,0.058969,-0.015637,0.022327,0.503000
std,1.021848,1.004281,1.006910,1.392738,1.268761,1.029279,1.267490,0.992629,1.000664,1.135131,0.500241
min,-3.718638,-3.116027,-3.534257,-4.999018,-2.587178,-3.250031,-4.932878,-3.187779,-2.819987,-2.071129,0.000000
25%,-0.685005,-0.657545,-0.647051,-1.057938,-0.981320,-0.722970,-0.855392,-0.598669,-0.693330,-1.050201,0.000000
50%,-0.030546,0.045869,0.040586,0.204506,-0.317137,-0.022343,0.148199,0.052208,0.018807,-0.037530,1.000000
75%,0.662124,0.701601,0.731615,1.061181,1.017388,0.596557,1.020255,0.722446,0.641338,0.760782,1.000000
max,2.765266,2.658705,3.357941,3.477210,3.954873,3.206344,2.343380,3.600187,3.477044,4.124285,1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      1000 non-null   float64
 1   job_satisfaction         1000 non-null   float64
 2   balance                  1000 non-null   float64
 3   duration_last_call       1000 non-null   float64
 4   num_contacts_last_month  1000 non-null   float64
 5   has_housing_loan         1000 non-null   float64
 6   has_personal_loan        1000 non-null   float64
 7   communication_type       1000 non-null   float64
 8   days_since_last_contact  1000 non-null   float64
 9   campaign_response_score  1000 non-null   float64
 10  subscribed               1000 non-null   int64
dtypes: float64(10), int64(1)
memory usage: 86.1 KB

In [6]:
X = df.drop("subscribed", axis = 1)
y = df["subscribed"]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state=15)

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
logistic = LogisticRegression()
logistic.fit(X_train, y_train)
y_pred = logistic.predict(X_test)

In [10]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1])

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [12]:
score = accuracy_score(y_pred, y_test)
print("score : ", score)
print(classification_report(y_pred, y_test))
print("confusion matric : \n", confusion_matrix(y_pred, y_test))

score :  0.92
              precision    recall  f1-score   support

           0       0.92      0.91      0.92       147
           1       0.92      0.93      0.92       153

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

confusion matric :
 [[134  13]
 [ 11 142]]

In [13]:
# hyperparameter tuning

In [14]:
model = LogisticRegression()

In [15]:
penalty = ["l1", "l2", "elasticnet"]
c_values = [100, 10, 1, 0.1, 0.001]
solver = ["newton-cg", "lbfgs", "liblinear", "saf", "saga", "newton-cholesky"]

In [16]:
params = dict(penalty=penalty, C=c_values, solver=solver)

In [17]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1, 0.1, 0.001],
 'solver': ['newton-cg',
  'lbfgs',
  'liblinear',
  'saf',
  'saga',
  'newton-cholesky']}

In [18]:
# grid search CV

In [19]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [20]:
cv = StratifiedKFold()

In [21]:
grid = GridSearchCV(estimator = model, param_grid = params, cv=cv, scoring="accuracy", n_jobs=-1)

In [22]:
import warnings
warnings.filterwarnings('ignore')
grid.fit(X_train, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.001],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'saf',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [23]:
grid.best_params_

{'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}

In [24]:
grid.best_score_

np.float64(0.9228571428571429)

In [25]:
y_pred = grid.predict(X_test)

In [26]:
score = accuracy_score(y_pred, y_test)
print("score : ", score)
print(classification_report(y_pred, y_test))
print("confusion matric : \n", confusion_matrix(y_pred, y_test))

score :  0.9233333333333333
              precision    recall  f1-score   support

           0       0.94      0.90      0.92       152
           1       0.90      0.95      0.92       148

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

confusion matric :
 [[137  15]
 [  8 140]]

In [27]:
# random search CV

In [28]:
from sklearn.model_selection import RandomizedSearchCV

In [29]:
model = LogisticRegression()

In [30]:
randomcv = RandomizedSearchCV(estimator = model, param_distributions = params, cv=5, n_iter=10, scoring ="accuracy")

In [31]:
import warnings
warnings.filterwarnings('ignore')
randomcv.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1, 0.1, 0.001],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'saf', 'saga',
                                                   'newton-cholesky']},
                   scoring='accuracy')

In [32]:
randomcv.best_params_

{'solver': 'newton-cholesky', 'penalty': 'l2', 'C': 0.1}

In [33]:
randomcv.best_score_

np.float64(0.9214285714285715)

In [34]:
y_pred = randomcv.predict(X_test)
print("score : ", score)
print(classification_report(y_pred, y_test))
print("confusion matric : \n", confusion_matrix(y_pred, y_test))

score :  0.9233333333333333
              precision    recall  f1-score   support

           0       0.94      0.90      0.92       151
           1       0.90      0.94      0.92       149

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

confusion matric :
 [[136  15]
 [  9 140]]